[package]
name = "quic-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
s2n-quic = "1"
tokio = { version = "1.26.0", features = ["full"] }
log = "0.4"
net = { path = "../net" }
